//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloMR : DbContext
    {
        public ModeloMR()
            : base("name=ModeloMR")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_aerolinea> tb_aerolinea { get; set; }
        public virtual DbSet<tb_agencia> tb_agencia { get; set; }
        public virtual DbSet<tb_bancoagencia> tb_bancoagencia { get; set; }
        public virtual DbSet<tb_cadenahotelera> tb_cadenahotelera { get; set; }
        public virtual DbSet<tb_categoria> tb_categoria { get; set; }
        public virtual DbSet<tb_ciudad> tb_ciudad { get; set; }
        public virtual DbSet<tb_contactohotel> tb_contactohotel { get; set; }
        public virtual DbSet<tb_detalleingresohotel> tb_detalleingresohotel { get; set; }
        public virtual DbSet<tb_hotel> tb_hotel { get; set; }
        public virtual DbSet<tb_impuestos> tb_impuestos { get; set; }
        public virtual DbSet<tb_ingresohotel> tb_ingresohotel { get; set; }
        public virtual DbSet<tb_moneda> tb_moneda { get; set; }
        public virtual DbSet<tb_pais> tb_pais { get; set; }
        public virtual DbSet<tb_tipocategoria> tb_tipocategoria { get; set; }
        public virtual DbSet<tb_tipohabitacion> tb_tipohabitacion { get; set; }
        public virtual DbSet<tb_usuario> tb_usuario { get; set; }
        public virtual DbSet<tb_vigencia> tb_vigencia { get; set; }
        public virtual DbSet<tb_zona> tb_zona { get; set; }
    }
}
