//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_aerolinea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_aerolinea()
        {
            this.tb_lineaerea_paquete = new HashSet<tb_lineaerea_paquete>();
            this.tb_tarifa_aerea = new HashSet<tb_tarifa_aerea>();
        }
    
        public int idaerolinea { get; set; }
        public string NombreComercial { get; set; }
        public Nullable<int> Zona { get; set; }
        public Nullable<int> telefono1 { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<int> Pais { get; set; }
        public Nullable<int> telefono2 { get; set; }
        public string Ruc { get; set; }
        public Nullable<int> Destino { get; set; }
        public string Paginaweb { get; set; }
        public string correofacturacion { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> BancoAfiliado { get; set; }
        public string logo { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public Nullable<int> usuarioregistro { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
        public Nullable<int> usuariomodificacion { get; set; }
    
        public virtual tb_categoria tb_categoria { get; set; }
        public virtual tb_ciudad tb_ciudad { get; set; }
        public virtual tb_pais tb_pais { get; set; }
        public virtual tb_zona tb_zona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_lineaerea_paquete> tb_lineaerea_paquete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tarifa_aerea> tb_tarifa_aerea { get; set; }
    }
}
