//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_agencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_agencia()
        {
            this.tb_bancoagencia = new HashSet<tb_bancoagencia>();
            this.tb_usuario1 = new HashSet<tb_usuario>();
        }
    
        public int idAgencia { get; set; }
        public Nullable<int> tipodocumento { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Promotor { get; set; }
        public Nullable<int> retenedor { get; set; }
        public Nullable<int> idZona { get; set; }
        public string Png_En_alta_vertical { get; set; }
        public Nullable<int> documentousuario { get; set; }
        public Nullable<int> Telefono1 { get; set; }
        public Nullable<decimal> Linea_Credito { get; set; }
        public Nullable<decimal> Retencion { get; set; }
        public Nullable<int> idPais { get; set; }
        public string png_en_alta_horizontal { get; set; }
        public string Numero_de_Ruc { get; set; }
        public Nullable<int> Telefono2 { get; set; }
        public Nullable<int> Formapago { get; set; }
        public string Cta_Detraccion { get; set; }
        public Nullable<int> idCiudad { get; set; }
        public string Pie_de_Pagina_Flyers { get; set; }
        public string RazonSocial { get; set; }
        public string correo { get; set; }
        public Nullable<int> Vigente { get; set; }
        public string Logo { get; set; }
        public string Color { get; set; }
        public string Encabezado_landing_reps { get; set; }
        public string Landing_MR { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public Nullable<int> usuarioregistro { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
        public Nullable<int> usuariomodificacion { get; set; }
    
        public virtual tb_categoria tb_categoria { get; set; }
        public virtual tb_categoria tb_categoria1 { get; set; }
        public virtual tb_ciudad tb_ciudad { get; set; }
        public virtual tb_pais tb_pais { get; set; }
        public virtual tb_zona tb_zona { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual tb_vigencia tb_vigencia { get; set; }
        public virtual tb_categoria tb_categoria2 { get; set; }
        public virtual tb_vigencia tb_vigencia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_bancoagencia> tb_bancoagencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuario> tb_usuario1 { get; set; }
    }
}
