//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cadenahotelera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cadenahotelera()
        {
            this.tb_hotel = new HashSet<tb_hotel>();
            this.tb_tipohabitacion = new HashSet<tb_tipohabitacion>();
            this.tb_servicioshotel = new HashSet<tb_servicioshotel>();
        }
    
        public int idCadenaHotelera { get; set; }
        public string nombreCadenaHotelera { get; set; }
        public Nullable<int> idZona { get; set; }
        public Nullable<int> idPais { get; set; }
        public Nullable<int> idCiudad { get; set; }
        public string DireccionCadenaHotelera { get; set; }
        public string ContactoCadenaHotelera { get; set; }
        public string CorreoCadenaHotelera { get; set; }
        public string Telefono1CadenaHotelera { get; set; }
        public string Telefono2CadenaHotelera { get; set; }
        public string LogoCadenaHotelera { get; set; }
        public string PaginaWebCadenaHotelera { get; set; }
        public Nullable<int> idVigencia { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public Nullable<int> usuarioregistro { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
        public Nullable<int> usuariomodificacion { get; set; }
    
        public virtual tb_ciudad tb_ciudad { get; set; }
        public virtual tb_pais tb_pais { get; set; }
        public virtual tb_vigencia tb_vigencia { get; set; }
        public virtual tb_zona tb_zona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_hotel> tb_hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tipohabitacion> tb_tipohabitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_servicioshotel> tb_servicioshotel { get; set; }
    }
}
