//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ciudad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ciudad()
        {
            this.tb_agencia = new HashSet<tb_agencia>();
            this.tb_cadenahotelera = new HashSet<tb_cadenahotelera>();
            this.tb_hotel = new HashSet<tb_hotel>();
            this.tb_aerolinea = new HashSet<tb_aerolinea>();
            this.tb_serviciosgenerales = new HashSet<tb_serviciosgenerales>();
            this.tb_serviciolineaaerea = new HashSet<tb_serviciolineaaerea>();
            this.tb_serviciolineaaerea1 = new HashSet<tb_serviciolineaaerea>();
            this.tb_serviciolineaaerea2 = new HashSet<tb_serviciolineaaerea>();
            this.tb_serviciolineaaerea3 = new HashSet<tb_serviciolineaaerea>();
            this.tb_serviciolineaaerea4 = new HashSet<tb_serviciolineaaerea>();
            this.tb_serviciosgenerales1 = new HashSet<tb_serviciosgenerales>();
        }
    
        public int idCiudad { get; set; }
        public string nombreCiudad { get; set; }
        public string CodigoCiudad { get; set; }
        public Nullable<int> idPais { get; set; }
        public Nullable<int> idZona { get; set; }
        public string fotoCiudad { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public Nullable<int> usuarioregistro { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
        public Nullable<int> usuariomodificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_agencia> tb_agencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cadenahotelera> tb_cadenahotelera { get; set; }
        public virtual tb_pais tb_pais { get; set; }
        public virtual tb_zona tb_zona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_hotel> tb_hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_aerolinea> tb_aerolinea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_serviciosgenerales> tb_serviciosgenerales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_serviciolineaaerea> tb_serviciolineaaerea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_serviciolineaaerea> tb_serviciolineaaerea1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_serviciolineaaerea> tb_serviciolineaaerea2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_serviciolineaaerea> tb_serviciolineaaerea3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_serviciolineaaerea> tb_serviciolineaaerea4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_serviciosgenerales> tb_serviciosgenerales1 { get; set; }
    }
}
