//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_detalletarifaaerea
    {
        public int id_detalle_tarifa_aerea { get; set; }
        public Nullable<int> id_tarifa_aerea { get; set; }
        public string impuesto { get; set; }
        public Nullable<decimal> precio_impuesto { get; set; }
    
        public virtual tb_tarifa_aerea tb_tarifa_aerea { get; set; }
    }
}
