//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_detalleingresohotel
    {
        public int idDetalleIngresoHotel { get; set; }
        public Nullable<int> idIngresoHotel { get; set; }
        public Nullable<int> idTipoHabitacion { get; set; }
        public Nullable<decimal> doble { get; set; }
        public Nullable<decimal> doblereal { get; set; }
        public Nullable<decimal> triple { get; set; }
        public Nullable<decimal> triplereal { get; set; }
        public Nullable<decimal> cuadruple { get; set; }
        public Nullable<decimal> cuadruplereal { get; set; }
        public Nullable<decimal> simple { get; set; }
        public Nullable<decimal> simplereal { get; set; }
        public Nullable<decimal> quintuple { get; set; }
        public Nullable<decimal> quituplereal { get; set; }
        public Nullable<decimal> sextuple { get; set; }
        public Nullable<decimal> sextuplereal { get; set; }
        public Nullable<decimal> child1 { get; set; }
        public Nullable<decimal> child1real { get; set; }
        public Nullable<int> edad1child1 { get; set; }
        public Nullable<int> edad2child1 { get; set; }
        public Nullable<decimal> child2 { get; set; }
        public Nullable<decimal> child2real { get; set; }
        public Nullable<int> edad1child2 { get; set; }
        public Nullable<int> edad2child2 { get; set; }
        public Nullable<decimal> child3 { get; set; }
        public Nullable<decimal> child3real { get; set; }
        public Nullable<int> edad1child3 { get; set; }
        public Nullable<int> edad2child3 { get; set; }
        public Nullable<decimal> infante { get; set; }
        public Nullable<decimal> infantereal { get; set; }
        public Nullable<int> edadinfante1 { get; set; }
        public Nullable<int> edadinfante2 { get; set; }
        public Nullable<int> capmaximaadu { get; set; }
        public Nullable<int> capmaximanin { get; set; }
        public Nullable<int> supmontodoble { get; set; }
        public Nullable<int> supporcentajedoble { get; set; }
        public Nullable<int> supmontotriple { get; set; }
        public Nullable<int> supporcentajetriple { get; set; }
        public Nullable<int> tercerpaxmonto { get; set; }
        public Nullable<int> tercerpaxporcentaje { get; set; }
        public Nullable<int> supmontocuadruple { get; set; }
        public Nullable<int> supporcentajecuadruple { get; set; }
        public Nullable<int> cuartopaxmonto { get; set; }
        public Nullable<int> cuartopaxporcentaje { get; set; }
        public Nullable<int> supmontosimple { get; set; }
        public Nullable<int> supporcentajesimple { get; set; }
        public Nullable<int> supmontoquintuple { get; set; }
        public Nullable<int> supporcentajequintuple { get; set; }
        public Nullable<int> quintopaxmonto { get; set; }
        public Nullable<int> quintopaxporcentaje { get; set; }
        public Nullable<int> supmontosextuple { get; set; }
        public Nullable<int> supporcentajesextuple { get; set; }
        public Nullable<int> sextopaxmonto { get; set; }
        public Nullable<int> sextopaxporcentaje { get; set; }
        public Nullable<int> supmontochild1 { get; set; }
        public Nullable<int> supporcentajechild1 { get; set; }
        public Nullable<int> supmontochild2 { get; set; }
        public Nullable<int> supporcentajechild2 { get; set; }
        public Nullable<int> supmontochild3 { get; set; }
        public Nullable<int> supporcentajechild3 { get; set; }
        public Nullable<int> supmontoinfante { get; set; }
        public Nullable<int> supporcentajeinfante { get; set; }
        public Nullable<int> serviciohabitacion1 { get; set; }
        public Nullable<int> serviciomonto1doble { get; set; }
        public Nullable<int> serviciomonto1triple { get; set; }
        public Nullable<int> serviciomonto1cuadruple { get; set; }
        public Nullable<int> serviciomonto1simple { get; set; }
        public Nullable<int> serviciomonto1quintuple { get; set; }
        public Nullable<int> serviciomonto1sextuple { get; set; }
        public Nullable<int> servicioporcentaje1doble { get; set; }
        public Nullable<int> servicioporcentaje1triple { get; set; }
        public Nullable<int> servicioporcentaje1cuadruple { get; set; }
        public Nullable<int> servicioporcentaje1simple { get; set; }
        public Nullable<int> servicioporcentaje1quintuple { get; set; }
        public Nullable<int> servicioporcentaje1sextuple { get; set; }
        public Nullable<int> serviciohabitacion2 { get; set; }
        public Nullable<int> serviciomonto2doble { get; set; }
        public Nullable<int> serviciomonto2triple { get; set; }
        public Nullable<int> serviciomonto2cuadruple { get; set; }
        public Nullable<int> serviciomonto2simple { get; set; }
        public Nullable<int> serviciomonto2quintuple { get; set; }
        public Nullable<int> serviciomonto2sextuple { get; set; }
        public Nullable<int> servicioporcentaje2doble { get; set; }
        public Nullable<int> servicioporcentaje2triple { get; set; }
        public Nullable<int> servicioporcentaje2cuadruple { get; set; }
        public Nullable<int> servicioporcentaje2simple { get; set; }
        public Nullable<int> servicioporcentaje2quintuple { get; set; }
        public Nullable<int> servicioporcentaje2sextuple { get; set; }
        public Nullable<int> preciserviciodoble1 { get; set; }
        public Nullable<int> preciserviciotriple1 { get; set; }
        public Nullable<int> preciserviciocuadruple1 { get; set; }
        public Nullable<int> preciserviciosimple1 { get; set; }
        public Nullable<int> preciservicioquintuple1 { get; set; }
        public Nullable<int> preciserviciosextuple1 { get; set; }
        public Nullable<int> preciserviciodoble2 { get; set; }
        public Nullable<int> preciserviciotriple2 { get; set; }
        public Nullable<int> preciserviciocuadruple2 { get; set; }
        public Nullable<int> preciserviciosimple2 { get; set; }
        public Nullable<int> preciservicioquintuple2 { get; set; }
        public Nullable<int> preciserviciosextuple2 { get; set; }
    
        public virtual tb_categoria tb_categoria { get; set; }
        public virtual tb_categoria tb_categoria1 { get; set; }
        public virtual tb_tipohabitacion tb_tipohabitacion { get; set; }
        public virtual tb_ingresohotel tb_ingresohotel { get; set; }
    }
}
