//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_detalletarifastopovers
    {
        public int id_detalle_tarifa_stopovers { get; set; }
        public Nullable<int> id_tarifa_aerea { get; set; }
        public Nullable<int> id_pais { get; set; }
        public Nullable<int> id_ciudad { get; set; }
    
        public virtual tb_ciudad tb_ciudad { get; set; }
        public virtual tb_tarifa_aerea tb_tarifa_aerea { get; set; }
        public virtual tb_pais tb_pais { get; set; }
    }
}
