//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_impuestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_impuestos()
        {
            this.tb_serviciolineaaerea = new HashSet<tb_serviciolineaaerea>();
            this.tb_serviciolineaaerea1 = new HashSet<tb_serviciolineaaerea>();
            this.tb_serviciolineaaerea2 = new HashSet<tb_serviciolineaaerea>();
            this.tb_serviciolineaaerea3 = new HashSet<tb_serviciolineaaerea>();
            this.tb_serviciolineaaerea4 = new HashSet<tb_serviciolineaaerea>();
            this.tb_serviciolineaaerea5 = new HashSet<tb_serviciolineaaerea>();
        }
    
        public int idImpuestos { get; set; }
        public string nombreImpuesto { get; set; }
        public Nullable<decimal> precioImpuesto { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public Nullable<int> usuarioregistro { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
        public Nullable<int> usuariomodificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_serviciolineaaerea> tb_serviciolineaaerea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_serviciolineaaerea> tb_serviciolineaaerea1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_serviciolineaaerea> tb_serviciolineaaerea2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_serviciolineaaerea> tb_serviciolineaaerea3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_serviciolineaaerea> tb_serviciolineaaerea4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_serviciolineaaerea> tb_serviciolineaaerea5 { get; set; }
    }
}
