//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_lineaerea_paquete
    {
        public int idLineaaereaPaquete { get; set; }
        public Nullable<int> idPaquete { get; set; }
        public Nullable<int> idLineaAerea { get; set; }
        public string clase { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual tb_aerolinea tb_aerolinea { get; set; }
        public virtual tb_paquete tb_paquete { get; set; }
    }
}
