//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_paquete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_paquete()
        {
            this.tb_hotel_paquete = new HashSet<tb_hotel_paquete>();
            this.tb_lineaerea_paquete = new HashSet<tb_lineaerea_paquete>();
            this.tb_servicios_paquete = new HashSet<tb_servicios_paquete>();
        }
    
        public int idPaquete { get; set; }
        public Nullable<int> incentivo { get; set; }
        public Nullable<decimal> factor { get; set; }
        public Nullable<int> comision { get; set; }
        public Nullable<System.DateTime> fechacompra { get; set; }
        public Nullable<int> seccion { get; set; }
        public Nullable<int> tematica { get; set; }
        public Nullable<int> moneda { get; set; }
        public Nullable<decimal> tipocambio { get; set; }
        public string nombrepaquete { get; set; }
        public Nullable<System.DateTime> tempviajeini { get; set; }
        public Nullable<System.DateTime> tempviajefin { get; set; }
        public Nullable<int> zona { get; set; }
        public Nullable<int> pais { get; set; }
        public Nullable<int> destino1 { get; set; }
        public Nullable<int> destino2 { get; set; }
        public string flyer { get; set; }
        public string word { get; set; }
        public Nullable<int> tarjetaasistencia { get; set; }
        public string incluye { get; set; }
        public string notas { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public Nullable<int> usuariocreacion { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
        public Nullable<int> usuariomodificacion { get; set; }
    
        public virtual tb_categoria tb_categoria { get; set; }
        public virtual tb_ciudad tb_ciudad { get; set; }
        public virtual tb_ciudad tb_ciudad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_hotel_paquete> tb_hotel_paquete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_lineaerea_paquete> tb_lineaerea_paquete { get; set; }
        public virtual tb_moneda tb_moneda { get; set; }
        public virtual tb_pais tb_pais { get; set; }
        public virtual tb_tarjetaasistencia tb_tarjetaasistencia { get; set; }
        public virtual tb_tematica tb_tematica { get; set; }
        public virtual tb_zona tb_zona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_servicios_paquete> tb_servicios_paquete { get; set; }
    }
}
