//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_paquete
    {
        public int idPaquete { get; set; }
        public Nullable<int> idZona { get; set; }
        public Nullable<int> idPais { get; set; }
        public Nullable<int> idCiudad { get; set; }
        public Nullable<System.DateTime> fecha_compra_in { get; set; }
        public Nullable<System.DateTime> fecha_compra_out { get; set; }
        public Nullable<System.DateTime> fecha_viajes_in { get; set; }
        public Nullable<System.DateTime> fecha_viaje_out { get; set; }
        public Nullable<int> idCadenaH { get; set; }
        public Nullable<int> idHotelH { get; set; }
        public Nullable<int> idTipoHabitacionH { get; set; }
        public string acomodacionH { get; set; }
        public Nullable<decimal> precioH { get; set; }
        public Nullable<int> idOperadorT { get; set; }
        public Nullable<int> idCiudadT { get; set; }
        public string planT { get; set; }
        public Nullable<decimal> precioT { get; set; }
        public Nullable<int> idOperadorTA { get; set; }
        public Nullable<int> planTA { get; set; }
        public Nullable<decimal> precioTA { get; set; }
        public Nullable<decimal> incentivo { get; set; }
        public Nullable<decimal> factor { get; set; }
        public Nullable<int> aerolinea { get; set; }
        public Nullable<int> npax { get; set; }
        public Nullable<decimal> precio_A { get; set; }
        public Nullable<decimal> precio_TTA { get; set; }
        public Nullable<decimal> preciototal { get; set; }
    
        public virtual tb_aerolinea tb_aerolinea { get; set; }
        public virtual tb_cadenahotelera tb_cadenahotelera { get; set; }
        public virtual tb_ciudad tb_ciudad { get; set; }
        public virtual tb_ciudad tb_ciudad1 { get; set; }
        public virtual tb_hotel tb_hotel { get; set; }
        public virtual tb_pais tb_pais { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual tb_usuario tb_usuario1 { get; set; }
        public virtual tb_tipohabitacion tb_tipohabitacion { get; set; }
        public virtual tb_zona tb_zona { get; set; }
        public virtual tb_tarjetaasistencia tb_tarjetaasistencia { get; set; }
    }
}
