//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_paquete
    {
        public int idPaquete { get; set; }
        public Nullable<int> idZona { get; set; }
        public Nullable<int> idPais { get; set; }
        public Nullable<int> idCiudad { get; set; }
        public Nullable<System.DateTime> fecha_compra_in { get; set; }
        public Nullable<System.DateTime> fecha_compra_out { get; set; }
        public Nullable<System.DateTime> fecha_viajes_in { get; set; }
        public Nullable<System.DateTime> fecha_viaje_out { get; set; }
        public Nullable<int> idCadenaH { get; set; }
        public Nullable<int> idHotelH { get; set; }
        public Nullable<int> idTipoHabitacionH { get; set; }
        public Nullable<int> tarifaH { get; set; }
        public Nullable<int> idOperadorT { get; set; }
        public Nullable<int> idCiudadT { get; set; }
        public string planT { get; set; }
        public Nullable<decimal> precioT { get; set; }
        public Nullable<int> idOperadorTA { get; set; }
        public Nullable<int> planTA { get; set; }
        public Nullable<decimal> precioTA { get; set; }
        public Nullable<decimal> incentivo { get; set; }
        public Nullable<decimal> factor { get; set; }
        public Nullable<int> aerolinea { get; set; }
        public string incluye { get; set; }
        public string no_incluye { get; set; }
        public string notas_generales { get; set; }
        public Nullable<int> rangoT1 { get; set; }
        public Nullable<int> rangoT2 { get; set; }
        public string cabeceraTable { get; set; }
        public Nullable<int> edad1child1__ { get; set; }
        public Nullable<int> edad1child2__ { get; set; }
        public Nullable<int> edad1child3__ { get; set; }
        public Nullable<int> edad1infante { get; set; }
        public Nullable<int> edad2child1 { get; set; }
        public Nullable<int> edad2child2 { get; set; }
        public Nullable<int> edad2child3 { get; set; }
        public Nullable<int> edad2infante { get; set; }
        public Nullable<decimal> doblereal { get; set; }
        public Nullable<decimal> triplereal { get; set; }
        public Nullable<decimal> simplereal { get; set; }
        public Nullable<decimal> cuadruplereal { get; set; }
        public Nullable<decimal> quintuplereal { get; set; }
        public Nullable<decimal> sextuplereal { get; set; }
        public Nullable<decimal> infantereal { get; set; }
        public Nullable<decimal> child1real { get; set; }
        public Nullable<decimal> child2real { get; set; }
        public Nullable<decimal> child3real { get; set; }
        public string titulo1 { get; set; }
        public string titulo2 { get; set; }
        public string titulo3 { get; set; }
        public Nullable<int> estado { get; set; }
        public string imagen1 { get; set; }
        public string imagen2 { get; set; }
        public string flyer1 { get; set; }
        public string flyer2 { get; set; }
    
        public virtual tb_aerolinea tb_aerolinea { get; set; }
        public virtual tb_cadenahotelera tb_cadenahotelera { get; set; }
        public virtual tb_ciudad tb_ciudad { get; set; }
        public virtual tb_ciudad tb_ciudad1 { get; set; }
        public virtual tb_hotel tb_hotel { get; set; }
        public virtual tb_pais tb_pais { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual tb_usuario tb_usuario1 { get; set; }
        public virtual tb_tipohabitacion tb_tipohabitacion { get; set; }
        public virtual tb_zona tb_zona { get; set; }
        public virtual tb_tarjetaasistencia tb_tarjetaasistencia { get; set; }
    }
}
