//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_serviciosgenerales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_serviciosgenerales()
        {
            this.tb_detalleserviciosgenerales = new HashSet<tb_detalleserviciosgenerales>();
        }
    
        public int idServiciosgenerales { get; set; }
        public Nullable<System.DateTime> viajaini { get; set; }
        public Nullable<System.DateTime> viajefin { get; set; }
        public Nullable<System.DateTime> compraini { get; set; }
        public Nullable<System.DateTime> comprafin { get; set; }
        public Nullable<int> tiposervicio { get; set; }
        public Nullable<int> tipotarifa { get; set; }
        public Nullable<int> desde { get; set; }
        public Nullable<int> hasta { get; set; }
        public Nullable<decimal> factor { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public Nullable<int> usuarioregistro { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
        public Nullable<int> usuariomodificacion { get; set; }
    
        public virtual tb_categoria tb_categoria { get; set; }
        public virtual tb_categoria tb_categoria1 { get; set; }
        public virtual tb_ciudad tb_ciudad { get; set; }
        public virtual tb_ciudad tb_ciudad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalleserviciosgenerales> tb_detalleserviciosgenerales { get; set; }
    }
}
