//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_servicioshotel
    {
        public int idServiciohotel { get; set; }
        public Nullable<System.DateTime> viajaini { get; set; }
        public Nullable<System.DateTime> viajefin { get; set; }
        public Nullable<System.DateTime> compraini { get; set; }
        public Nullable<System.DateTime> comprafin { get; set; }
        public Nullable<int> promociones { get; set; }
        public Nullable<int> idCadena { get; set; }
        public Nullable<int> idHotel { get; set; }
        public Nullable<int> idTipoHabitacion { get; set; }
        public Nullable<int> tipoalimentacion { get; set; }
        public Nullable<int> noches { get; set; }
        public Nullable<int> minnoches { get; set; }
        public Nullable<int> comision { get; set; }
        public Nullable<int> tipotarifa { get; set; }
        public Nullable<decimal> valordoble { get; set; }
        public Nullable<decimal> nadoble { get; set; }
        public Nullable<decimal> realDoble { get; set; }
        public Nullable<decimal> valortriple { get; set; }
        public Nullable<decimal> natriple { get; set; }
        public Nullable<decimal> realTriple { get; set; }
        public Nullable<decimal> valorsimple { get; set; }
        public Nullable<decimal> nasimple { get; set; }
        public Nullable<decimal> realSimple { get; set; }
        public Nullable<decimal> ValorCuadruple { get; set; }
        public Nullable<decimal> NACuadruple { get; set; }
        public Nullable<decimal> realCuadruple { get; set; }
        public Nullable<decimal> ValorQuintuple { get; set; }
        public Nullable<decimal> NAQuintuple { get; set; }
        public Nullable<decimal> realQuintuple { get; set; }
        public Nullable<decimal> ValorSextuple { get; set; }
        public Nullable<decimal> NASextuple { get; set; }
        public Nullable<decimal> realSextuple { get; set; }
        public Nullable<decimal> ValorChild1 { get; set; }
        public Nullable<decimal> NAChild1 { get; set; }
        public Nullable<decimal> Edad1Child1 { get; set; }
        public Nullable<decimal> Edad2Child1 { get; set; }
        public Nullable<decimal> realChild1 { get; set; }
        public Nullable<decimal> ValorChild2 { get; set; }
        public Nullable<decimal> NAChild2 { get; set; }
        public Nullable<decimal> Edad1Child2 { get; set; }
        public Nullable<decimal> Edad2Child2 { get; set; }
        public Nullable<decimal> realChild2 { get; set; }
        public Nullable<decimal> ValorJunior { get; set; }
        public Nullable<decimal> NAJunior { get; set; }
        public Nullable<decimal> Edad1Junior { get; set; }
        public Nullable<decimal> Edad2Junior { get; set; }
        public Nullable<decimal> realJunior { get; set; }
        public Nullable<decimal> ValorInfante { get; set; }
        public Nullable<decimal> NAInfante { get; set; }
        public Nullable<decimal> Edad1Infante { get; set; }
        public Nullable<decimal> Edad2Infante { get; set; }
        public Nullable<decimal> realInfante { get; set; }
        public Nullable<decimal> factor { get; set; }
        public string notasgenerales { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public Nullable<int> usuarioregistro { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
        public Nullable<int> usuariomodificacion { get; set; }
    
        public virtual tb_cadenahotelera tb_cadenahotelera { get; set; }
        public virtual tb_categoria tb_categoria { get; set; }
        public virtual tb_categoria tb_categoria1 { get; set; }
        public virtual tb_categoria tb_categoria2 { get; set; }
        public virtual tb_hotel tb_hotel { get; set; }
        public virtual tb_tipohabitacion tb_tipohabitacion { get; set; }
    }
}
