//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_servicios_paquete
    {
        public int idServiciosPaquete { get; set; }
        public Nullable<int> idPaquete { get; set; }
        public Nullable<int> tiposervicio { get; set; }
        public Nullable<int> traslados { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual tb_categoria tb_categoria { get; set; }
        public virtual tb_paquete tb_paquete { get; set; }
        public virtual tb_traslado tb_traslado { get; set; }
    }
}
