//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tarjetaasistencia
    {
        public int idTarjetaasistencia { get; set; }
        public string nombreTarjetaasistencia { get; set; }
        public Nullable<int> idOperador { get; set; }
        public Nullable<int> cobertura { get; set; }
        public Nullable<decimal> costo { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
