//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_traslado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_traslado()
        {
            this.tb_detalleTraslado = new HashSet<tb_detalleTraslado>();
        }
    
        public int id_traslado { get; set; }
        public int id_operador { get; set; }
        public int id_puntosalida { get; set; }
        public Nullable<System.DateTime> fecha_vigencia { get; set; }
    
        public virtual tb_ciudad tb_ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalleTraslado> tb_detalleTraslado { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
