//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tarifa_aerea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_tarifa_aerea()
        {
            this.tb_detalletarifaaerea = new HashSet<tb_detalletarifaaerea>();
            this.tb_detalletarifablackouts = new HashSet<tb_detalletarifablackouts>();
            this.tb_detalletarifastopovers = new HashSet<tb_detalletarifastopovers>();
        }
    
        public int id_tarifa_aerea { get; set; }
        public Nullable<int> id_zona { get; set; }
        public Nullable<int> id_pais { get; set; }
        public Nullable<int> id_ciudad { get; set; }
        public string clase { get; set; }
        public Nullable<int> id_laerea { get; set; }
        public string dest_abre { get; set; }
        public Nullable<decimal> total_tarifa { get; set; }
        public Nullable<decimal> neto { get; set; }
        public string min_estadia { get; set; }
        public string max_estadia { get; set; }
        public Nullable<System.DateTime> time_compra_1 { get; set; }
        public Nullable<System.DateTime> time_compra_2 { get; set; }
        public string fecha_emisiion { get; set; }
        public Nullable<decimal> porc_chd { get; set; }
        public Nullable<decimal> prec_chd { get; set; }
        public Nullable<decimal> porc_inf { get; set; }
        public Nullable<decimal> prec_inf { get; set; }
        public Nullable<int> edad_chd_1 { get; set; }
        public Nullable<int> edad_chd_2 { get; set; }
        public Nullable<int> edad_inf_1 { get; set; }
        public Nullable<int> edad_inf_2 { get; set; }
        public string cod_fb { get; set; }
        public Nullable<System.DateTime> time_viaje_1 { get; set; }
        public Nullable<System.DateTime> time_viaje_2 { get; set; }
        public Nullable<decimal> queue { get; set; }
        public Nullable<decimal> igv { get; set; }
        public Nullable<int> estado { get; set; }
        public string tipo_tarifa { get; set; }
    
        public virtual tb_aerolinea tb_aerolinea { get; set; }
        public virtual tb_ciudad tb_ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalletarifaaerea> tb_detalletarifaaerea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalletarifablackouts> tb_detalletarifablackouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalletarifastopovers> tb_detalletarifastopovers { get; set; }
        public virtual tb_pais tb_pais { get; set; }
        public virtual tb_zona tb_zona { get; set; }
    }
}
