//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMundoRepresentaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_usuario()
        {
            this.tb_agencia = new HashSet<tb_agencia>();
            this.tb_paquete = new HashSet<tb_paquete>();
            this.tb_paquete1 = new HashSet<tb_paquete>();
            this.tb_tarjetaasistencia = new HashSet<tb_tarjetaasistencia>();
            this.tb_traslado = new HashSet<tb_traslado>();
        }
    
        public int idUsuario { get; set; }
        public Nullable<int> anexo_usuario { get; set; }
        public string apellidopaternousuario { get; set; }
        public string apellidomaternousuario { get; set; }
        public Nullable<int> areausuario { get; set; }
        public Nullable<int> Puesto_Empresa { get; set; }
        public Nullable<decimal> comisionusuario { get; set; }
        public string contactousuario { get; set; }
        public string contrasenausuario { get; set; }
        public string correousuario { get; set; }
        public string correosunatusuario { get; set; }
        public string ctadetraccionusuario { get; set; }
        public Nullable<System.DateTime> cumpleanosusuario { get; set; }
        public string direccionusuario { get; set; }
        public Nullable<int> documentousuario { get; set; }
        public Nullable<int> empresesa_usuario { get; set; }
        public Nullable<int> facturaelectronicausuario { get; set; }
        public Nullable<int> formapagousuario { get; set; }
        public Nullable<decimal> lineacreditousuario { get; set; }
        public Nullable<decimal> metausuario { get; set; }
        public string nombreusuario { get; set; }
        public string numerocontactousuario { get; set; }
        public string numerodocumentousuario { get; set; }
        public Nullable<int> idPais { get; set; }
        public string razonsocialusuario { get; set; }
        public Nullable<int> retenedorusuario { get; set; }
        public Nullable<int> sexousuario { get; set; }
        public string skypeusuario { get; set; }
        public Nullable<int> telefonousuario { get; set; }
        public Nullable<int> tipodocumento { get; set; }
        public string usuario { get; set; }
        public Nullable<int> vigenteusuario { get; set; }
        public Nullable<int> idZona { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public Nullable<int> usuarioregistro { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
        public Nullable<int> usuariomodificacion { get; set; }
        public Nullable<int> idAgencia { get; set; }
        public Nullable<int> TIPOUSUARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_agencia> tb_agencia { get; set; }
        public virtual tb_agencia tb_agencia1 { get; set; }
        public virtual tb_categoria tb_categoria { get; set; }
        public virtual tb_categoria tb_categoria1 { get; set; }
        public virtual tb_categoria tb_categoria2 { get; set; }
        public virtual tb_categoria tb_categoria3 { get; set; }
        public virtual tb_categoria tb_categoria4 { get; set; }
        public virtual tb_categoria tb_categoria5 { get; set; }
        public virtual tb_categoria tb_categoria6 { get; set; }
        public virtual tb_categoria tb_categoria7 { get; set; }
        public virtual tb_pais tb_pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_paquete> tb_paquete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_paquete> tb_paquete1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tarjetaasistencia> tb_tarjetaasistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_traslado> tb_traslado { get; set; }
        public virtual tb_vigencia tb_vigencia { get; set; }
        public virtual tb_zona tb_zona { get; set; }
        public virtual tb_vigencia tb_vigencia1 { get; set; }
        public virtual tb_vigencia tb_vigencia2 { get; set; }
    }
}
